### ISSUE TITLE
Got "SyntaxError: Unexpected token {"  error when I ran yarn start

### ISSUE THREAD

**Issue by imtmh** [shengnian/webpack2-react-redux-starter#1]
Log is below. I think its because its missing the support for object destructuring

```
myMac@myMac-mac ~/Work/PlayWing/webpack2-react-redux-starter (master *) $ yarn start
yarn start v0.21.3
$ better-npm-run start 
running better-npm-run in /Users/myMac/Work/webpack2-react-redux-starter
Executing script: start

to be executed: node bin/dev-server 
/Users/myMac/Work/webpack2-react-redux-starter/config/project.config.js:4
const { argv } = require('yargs')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myMac/Work/webpack2-react-redux-starter/bin/dev-server.js:1:79)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
error Command failed with exit code 1.
```

**Comment by shengnian** [comment]
can you show your node version and yarn version? my node version: v7.0.0, yarn version: 0.18.1 work good.
